version: "3.9"
services:
  nginx:
    #container_name: 
    image: nginx
    #build: .
    ports:
      - '80:80'

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root

  ansible:
    image: siddharthadmin/ansible-worker-node
    ports:
      - '8081:8080'
    
