version: '3.9'
# volumes:
#   # shared:
#   #    - /var/lib/docker/volumes/shared/_data
services:
  ansible-worker1:
    image: siddharthadmin/ansible-worker-node:latest
    container_name: d_node1
    restart: unless-stopped
    #tty: true
    # command:
    ports:
      - "8080:8080"
    
  ansible-worker2:
    image: siddharthadmin/ansible-worker-node:latest
    container_name: d_node2
    restart: unless-stopped
    #tty: true
    # command: 
    ports:
      - "8081:8081"
    
  ansible-worker3:
    image: siddharthadmin/ansible-worker-node:latest
    container_name: d_node3
    restart: unless-stopped
    #tty: true
    # command:
    ports:
      - "8083:8083"