version: "3"
services:
  ansible-app:
    #container_name: 
    image: siddharthadmin/ansible-worker-node:latest
    #build: .
    ports:
      - 8000-8999:8080

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    