version: "3"
services:
  nginx:
    #container_name: 
    image: nginx
    #build: .
    ports:
      - 8000-8999:8080

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
    