version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ready2go
      MYSQL_DATABASE: mysql-database
    ports:
      - "3306:3306"
    volumes:
      - shared:/var/lib/docker/volumes/shared/_data

volumes:
  shared:
