# version: "3"
# services:
#   nginx:
#     #container_name: 
#     image: nginx
#     #build: .
#     ports:
#       - '80:80'

  # mysqldb:
  #   container_name: mysqldb
  #   image: mysql
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     MYSQL_DATABASE: test
  #     MYSQL_ROOT_PASSWORD: root
    
version: '3'
services:
  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./logs:/usr/local/tomcat/logs
    restart: always